-- Run this SQL in your Supabase SQL Editor to set up the database

-- Create the courses table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  duration TEXT NOT NULL, -- e.g., "3 Months", "6 Weeks"
  amount DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create the registrations table
CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  email TEXT NOT NULL,
  mobile TEXT NOT NULL,
  address TEXT NOT NULL,
  course_id BIGINT REFERENCES courses(id),
  course_title TEXT, -- Storing snapshot in case course is deleted/changed
  amount_paid DECIMAL(10, 2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable Row Level Security (RLS) is recommended, but for this demo we will create an open policy
-- so the app works immediately without auth configuration complexity.
-- In a real production app, you would restrict these.

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON courses FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON courses FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON registrations FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON registrations FOR INSERT WITH CHECK (true);
